

volumes:
  postgres_data:
  static_data:
  media_data:
  certbot_conf:
  certbot_www:


networks:
  dev:
    driver: bridge


services:
  db:
    image: postgres:13.0-alpine
    container_name: shop.co-db
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - dev



  backend:
    build: ./backend
    container_name: shop.co-backend
    env_file: .env
    volumes:
      - static_data:/app/static
      - media_data:/app/media

    ports:
      - 8000:8000
    links:
      - db
    restart: always
    command: sh -c "python3 manage.py makemigrations &&
                    python3 manage.py migrate &&
                    python3 manage.py collectstatic --noinput &&
                    gunicorn DjangoProject2.wsgi:application --bind 0.0.0.0:8000"
    networks:
      - dev

  redis:
    image: redis:7.2.3-alpine
    container_name: shop.co-redis
    ports:
      - 6379:6379
    hostname: redis
    networks:
      - dev
    restart: unless-stopped

  #celery:
    #build: ./backend
    #container_name: bigcorp-celery
    #env_file: .env
    #depends_on:
      #- db
      #- redis
   # volumes:
      #- static_data:/app/static
    #restart: always
    #command: celery -A bigcorp worker --loglevel=info --beat

  nginx:
    image: nginx:latest
    container_name: shop.co-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_data:/app/static
      - media_data:/app/media
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    restart: always
    networks:
      - dev

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - dev


  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: abc123def456  # Replace with UUID
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
      - kafka_data:/tmp/kraft-combined-logs
      - ./server.properties:/etc/message-processor/server.properties  # Optional
    networks:
      - dev

  mongodb:
    image: mongodb/community-server:7.0-ubi
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      -
  connect:
    image: confluentinc/cp-kafka-connect:latest
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: 'message-processor:9092'
      CONNECT_REST_ADVERTISED_HOST_NAME: 'connect'
      CONNECT_GROUP_ID: 'connect-group'
      CONNECT_CONFIG_STORAGE_TOPIC: 'connect-configs'
      CONNECT_OFFSET_STORAGE_TOPIC: 'connect-offsets'
      CONNECT_STATUS_STORAGE_TOPIC: 'connect-status'
      CONNECT_KEY_CONVERTER: 'org.apache.message-processor.connect.json.JsonConverter'
      CONNECT_VALUE_CONVERTER: 'org.apache.message-processor.connect.json.JsonConverter'
      CONNECT_PLUGIN_PATH: '/usr/share/java,/usr/share/confluent-hub-components'
    depends_on:
      - kafka
      - mongodb
