# Generated by Django 5.1.4 on 2024-12-23 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_categories_alter_goods_options_goods_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='shop.categories'),
            preserve_default=False,
        ),
    ]
