# Generated by Django 5.1.4 on 2025-10-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='external_token',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Внешний токен'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_external_authenticated',
            field=models.BooleanField(default=False, verbose_name='Внешняя аутентификация подтверждена'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_image_processed',
            field=models.BooleanField(default=False, verbose_name='Изображение обработано'),
        ),
    ]
